[
    Dynamic, Provider("WMIProv"),
    WMI,
    Description ("AHA154x Setup Data Description (Operation Code 0Dh)"),
    guid ("{ea992010-b75b-11d0-a307-00aa006c3f30}"),
    HeaderName("AHA154SetupData"),
    GuidName1("Aha154xWmi_SetupData_Guid"),
    WmiExpense(0)
]
class AHA154xSetupDataGuid
{
    [read,key] String InstanceName;
    [read] boolean Active;

    [read, WmiDataId(1), WmiVersion(1)] uint8 SdtAndParityStatus;
    [read, WmiDataId(2), WmiVersion(1)] uint8 TransferSpeed;
    [read, WmiDataId(3), WmiVersion(1)] uint8 BusOnTime;
    [read, WmiDataId(4), WmiVersion(1)] uint8 BusOffTime;
    [read, WmiDataId(5), WmiVersion(1)] uint8 NumberOfMailboxes;
    [read, WmiDataId(6), WmiVersion(1)] uint8 MailboxAddressMsb;
    [read, WmiDataId(7), WmiVersion(1)] uint8 MailboxAddressMid;
    [read, WmiDataId(8), WmiVersion(1)] uint8 MailboxAddressLsb;
    [read, WmiDataId(9), WmiVersion(1)] uint8 SyncTransferAgreements0;
    [read, WmiDataId(10), WmiVersion(1)] uint8 SyncTransferAgreements1;
    [read, WmiDataId(11), WmiVersion(1)] uint8 SyncTransferAgreements2;
    [read, WmiDataId(12), WmiVersion(1)] uint8 SyncTransferAgreements3;
    [read, WmiDataId(13), WmiVersion(1)] uint8 SyncTransferAgreements4;
    [read, WmiDataId(14), WmiVersion(1)] uint8 SyncTransferAgreements5;
    [read, WmiDataId(15), WmiVersion(1)] uint8 SyncTransferAgreements6;
    [read, WmiDataId(16), WmiVersion(1)] uint8 SyncTransferAgreements7;
    [read, WmiDataId(17), WmiVersion(1)] uint8 DisconnectionOption;
    [read, WmiDataId(18), WmiVersion(1), max(20)] sint8 CustomerBanner[];
    [read, WmiDataId(19), WmiVersion(1)] uint8 AutoRetryOption;
    [read, WmiDataId(20), WmiVersion(1)] uint8 SwitchesOnBoard;
    [read, WmiDataId(21), WmiVersion(1)] uint16 FirmwareChecksum;
    [read, WmiDataId(22), WmiVersion(1)] uint8 BiosMailboxAddressMsb;
    [read, WmiDataId(23), WmiVersion(1)] uint8 BiosMailboxAddressMid;
    [read, WmiDataId(24), WmiVersion(1)] uint8 BiosMailboxAddressLsb;
    [read, WmiDataId(25), WmiVersion(1), max(211)] uint8 Reserved[];
};


