#############################################################################
#
#       Copyright (C) Microsoft Corporation 1996-99
#       All Rights Reserved.
#
#       Makefile for 1394api directory
#
#############################################################################
!IFDEF WIN95_BUILD

ROOT = ..\..\..\..

BLDPROJ=OPK3

WIN32=1
IS_32 = TRUE
IS_OEM = TRUE

VERSIONLIST = debug retail
COMMONMKFILE = 1394api.mk

!include $(ROOT)\DEV\MASTER.MK

!ELSE

!INCLUDE $(NTMAKEENV)\makefile.def

!ENDIF

