#############################################################################
#
#   THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY
#   KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
#   IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR
#   PURPOSE.
#
#   Copyright (c) 1992-2000 Microsoft Corporation
#
#   MSGSM32.ACM -- Microsoft ACM CODEC for GSM 6.10
#
#############################################################################
!INCLUDE $(NTMAKEENV)\makefile.def


