/**************************************************************************
**
**  THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY
**  KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
**  IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR
**  PURPOSE.
**
**  Copyright (c) 2000-2001 Microsoft Corporation. All Rights Reserved.
**
**************************************************************************/

// GFXProp.idl : IDL source for GFXProp.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (GFXProp.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
	[
		object,
		uuid(6F39F0CD-DC09-42A4-9E29-FB988E00EF67),
	
		helpstring("IGFXPropPages Interface"),
		pointer_default(unique)
	]
	interface IGFXPropPages : IUnknown
	{
	};

[
	uuid(97A68278-07A0-476F-9711-96D72712145C),
	version(1.0),
	helpstring("GFXProp 1.0 Type Library")
]
library GFXPROPLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(25957AEC-9A65-464B-AE00-8AB9F2ABC678),
		helpstring("GFXPropPages Class")
	]
	coclass GFXPropPages
	{
		[default] interface IGFXPropPages;
	};

	[
		uuid(1C29928A-5B53-4950-952F-5E7C6E86E91D),
		helpstring("GFXProperty Class")
	]
	coclass GFXProperty
	{
		interface IUnknown;
	};
};

