[Dynamic, Provider("WMIProv"),
 WMI,
 Description("PCIDRV driver information"),
 guid("{20E35E40-7179-4f89-A28C-12ED5A3CAAA5}"),
 locale("MS\\0x409")]
class PciDeviceInformation
{
    [key, read]
     string InstanceName;
    [read] boolean Active;

    [WmiDataId(1),
     read,
     write,
     Description("The DebugPrintLevel property indicates the debug output level of PCI driver.")]
    uint32 DebugPrintLevel;
};

[Dynamic, Provider("WMIProv"),
 WMI,
 Description("ConservationIdleTime"),
 guid("{0106A479-477C-4aef-91C2-DD9666D0F409}"),
 locale("MS\\0x409")]
class ConservationIdleTime
{
    [key, read]
     string InstanceName;
    [read] boolean Active;

    [WmiDataId(1),
     read,
     write,
     Description("This property allows you to get or set the idle detection timer value when the device is running on battery power.")]
    uint32 ConservationIdleTime;
};

[Dynamic, Provider("WMIProv"),
 WMI,
 Description("PerformanceIdleTime"),
 guid("{3E426488-5B3A-4353-B0FC-537FE8F82D07}"),
 locale("MS\\0x409")]
class PerformanceIdleTime
{
    [key, read]
     string InstanceName;
    [read] boolean Active;

    [WmiDataId(1),
     read,
     write,
     Description("This property allows you to get or set the idle detection timer value when the device is running on AC power.")]
    uint32 PerformanceIdleTime;
};

