
#############################################################################
#
#       Copyright (C) Microsoft Corporation 1998, 1999
#       All Rights Reserved.
#
#############################################################################

#
# DO NOT EDIT THIS FILE!!!  Edit .\sources. if you want to add a new source
# file to this component.  This file merely indirects to the real make file
# that is shared by all the driver components of Windows NT
#

!INCLUDE $(NTMAKEENV)\makefile.def



