import "oaidl.idl";
import "ocidl.idl";

[
    uuid(01CF74F5-A313-4cea-AAC7-D4A983B5B125)
]

library WIASampleExtLib
{
        importlib("stdole32.tlb");
        importlib("stdole2.tlb");

    [
        uuid(b6c280f7-0f07-11d3-94c7-00805f6596d2),
        helpstring("Shell extension class")
    ]
    coclass ShellExt
    {
        [default] interface IUnknown;
    };

    [
        uuid(edb8b35d-c15f-4e45-9658-50d7f8addb56),
        helpstring("WIA UI extension class")
    ]
    coclass WiaUIExtension
    {
        [default] interface IUnknown;
    };
};

